services:
  api:
    build: ./apps/api
    env_file: ./apps/api/.env
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  web:
    build:
      context: ./apps/web
      args:
        VITE_API_URL: http://localhost:3001
    ports:
      - "5173:80"
    depends_on:
      - api
