services:
  # api:
  #   build: 
  #     context: ./apps/api
  #   env_file: ./apps/api/.env
  #   ports:
  #     - "3001:3001"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   networks:
  #    - app-network

  web:
    build:
      context: ./apps/web
      args:
        VITE_API_URL: http://localhost:3001
    ports:
      - "5173:80"
    # depends_on:
    #   - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
     - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    # depends_on:
    #   - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
     - app-network

  grafana:
    image: grafana/grafana:9.5.15
    container_name: grafana
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER={user_name_here}
      - GF_SECURITY_ADMIN_PASSWORD={user_password_here}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
     - app-network

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MLFLOW_FLASK_SERVER_SECRET_KEY=ff29359abc659870d3e3a338c20b16d5cd9ade8d4bb632355f63d6dcc9676cb1
    volumes:
      - mlflow_data:/mlflow
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --allowed-hosts "mlflow:5000,localhost:*"
      --backend-store-uri sqlite:////mlflow/mlflow.db 
      --default-artifact-root /mlflow/artifacts 
      --app-name basic-auth
    networks:
     - app-network

volumes:
  mlflow_data:

networks:
  app-network:
    driver: bridge